services:
  mastodon:
    image: lscr.io/linuxserver/mastodon:latest
    env_file: .env.production
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - ./data:/config
    restart: always

  redis:
    image: redis:8
    volumes:
      - ./redis:/data
    command: ["redis-server", "--appendonly", "yes"]
    restart: always
